.PHONY: dev build test reset-db logs down

dev:
	./scripts/dev.sh

build:
	./scripts/build.sh

test:
	./scripts/test.sh

reset-db:
	./scripts/reset-db.sh

logs:
	docker compose logs -f

down:
	docker compose down
